export const jobCategory = [
    {'title': 'Information Technology', 
    'roles': [
    "Computer Scientist",
    "IT Professional",
    "UX Designer & UI Developer",
    "SQL Developer",
    "Back-End Developer",
    "Front-End Developer",
    "Full-Stack Developer",
    "Desktop Support",
    "Software Engineer",
    "Data Entry",
    "DevOps Engineer",
    "Computer Programmer",
    "Network Administrator",
    "Information Security Analyst",
    "Artificial Intelligence Engineer",
    "Cloud Architect",
    "IT Manager",
    "Technical Specialist",
    "Application Developer"
    ]
    },
    {'title': 'Marketing', 
    'roles': ['Marketing Specialist',
    'Marketing Manager',
    'Marketing Director',
    'Graphic Designer',
    'Marketing Research Analyst',
    'Marketing Communications Manager',
    'Marketing Consultant',
    'Product Manager',
    'Public Relations',
    'Social Media Assistant',
    'Brand Manager',
    'SEO Manager',
    'Content Marketing Manager',
    'Copywriter',
    'Media Buyer',
    'Digital Marketing Manager',
    'eCommerce Marketing Specialist',
    'Brand Strategist',
    'Vice President of Marketing',
    'Media Relations Coordinator'
    ]},
    {'title': 'Administrative', 
      'roles': [
        "Administrative Assistant",
        "Receptionist",
        "Office Manager",
        "Auditing Clerk",
        "Bookkeeper",
        "Account Executive",
        "Branch Manager",
        "Business Manager",
        "Quality Control Coordinator",
        "Administrative Manager",
        "Chief Executive Officer",
        "Business Analyst",
        "Risk Manager",
        "Human Resources",
        "Office Assistant",
        "Secretary",
        "Office Clerk",
        "File Clerk",
        "Account Collector",
        "Administrative Specialist",
        "Executive Assistant",
        "Program Administrator",
        "Program Manager",
        "Administrative Analyst",
        "Data Entry"
      ]
    },
    {'title': 'Researcher and Analyst', 
      'roles': ["Researcher",
      "Research Assistant",
      "Data Analyst",
      "Business Analyst",
      "Financial Analyst",
      "Biostatistician",
      "Title Researcher",
      "Market Researcher",
      "Title Analyst",
      "Medical Researcher"
      ]
    },
    {'title': 'Leadership', 
      'roles': ["Team Leader",
      "Manager",
      "Assistant Manager",
      "Executive",
      "Director",
      "Coordinator",
      "Administrator",
      "Controller",
      "Officer",
      "Organizer",
      "Supervisor",
      "Superintendent",
      "Head",
      "Overseer",
      "Chief",
      "Foreman",
      "Controller",
      "Principal",
      "President",
      "Lead"
      ]
    },
    {'title': 'Sales', 
      'roles': ["Sales Associate",
      "Sales Representative",
      "Sales Manager",
      "Retail Worker",
      "Store Manager",
      "Sales Representative",
      "Sales Manager",
      "Real Estate Broker",
      "Sales Associate",
      "Cashier",
      "Store Manager",
      "Account Executive",
      "Account Manager",
      "Area Sales Manager",
      "Direct Salesperson",
      "Director of Inside Sales",
      "Outside Sales Manager",
      "Sales Analyst",
      "Market Development Manager",
      "B2B Sales Specialist",
      "Sales Engineer",
      "Merchandising Associate"
      ]
    },
    {'title': 'Finance and Accounting', 
      'roles': ["Credit Authorizer",
      "Benefits Manager",
      "Credit Counselor",
      "Accountant",
      "Bookkeeper",
      "Accounting Analyst",
      "Accounting Director",
      "Accounts Payable Receivable Clerk",
      "Auditor",
      "Budget Analyst",
      "Controller",
      "Financial Analyst",
      "Finance Manager",
      "Economist",
      "Payroll Manager",
      "Payroll Clerk",
      "Financial Planner",
      "Financial Services Representative",
      "Finance Director",
      "Commercial Loan Office"
      ]
    },
    {'title': 'Operations', 
      'roles': ["Operations Manager",
      "Operations Assistant",
      "Operations Coordinator",
      "Operations Analyst",
      "Operations Director",
      "Vice President of Operations",
      "Operations Professional",
      "Scrum Master",
      "Continuous Improvement Lead",
      "Continuous Improvement Consultant"
      ]
    },
    {'title': 'Business Owner', 
      'roles': ["CEO",
      "Proprietor",
      "Principal",
      "Owner",
      "President",
      "Founder",
      "Administrator",
      "Director",
      "Managing Partner",
      "Managing Member"
      ]
    },
    {'title': 'C Level', 
      'roles': ["Chief Executive Officer",
      "Chief Operating Officer",
      "Chief Financial Officer",
      "Chief Information Officer",
      "Chief Technology Officer",
      "Chief Marketing Officer",
      "Chief Human Resources Officer",
      "Chief Data Officer",
      "Chief Product Officer",
      "Chief Customer Officer"
      ]
    },
    {'title': 'Customer Service', 
      'roles': ["Virtual Assistant",
      "Customer Service",
      "Customer Support",
      "Concierge",
      "Help Desk",
      "Customer Service Manager",
      "Technical Support Specialist",
      "Account Representative",
      "Client Service Specialist",
      "Customer Care Associate"
      ]
    },
    {'title': 'Engineering', 
      'roles': ["Engineer",
      "Mechanical Engineer",
      "Civil Engineer",
      "Electrical Engineer",
      "Assistant Engineer",
      "Chemical Engineer",
      "Chief Engineer",
      "Drafter",
      "Engineering Technician",
      "Geological Engineer",
      "Biological Engineer",
      "Maintenance Engineer",
      "Mining Engineer",
      "Nuclear Engineer",
      "Petroleum Engineer",
      "Plant Engineer",
      "Production Engineer",
      "Quality Engineer",
      "Safety Engineer",
      "Sales Engineer"
      ]
    },
    {'title': 'Teacher', 
      'roles': ["Mentor",
      "Online Tutor",
      "Teacher",
      "Teaching Assistant",
      "Substitute Teacher",
      "Preschool Teacher",
      "Test Scorer",
      "Online ESL Instructor",
      "Professor",
      "Assistant Professor"
      ]
    }
];