export const skills = [
    "C++",
"C",
"Java",
"Javascript",
"Perl",
"PHP",
"Python",
"Swift",
"Go",
"SQL",
"R",
"Ruby",
"Google Suite",
"Trello",
"Slack",
"Zapier",
"Zoom",
"JIRA",
"Salesforce",
"Budget planning",
"Risk management",
"Project planning",
"PM tools",
"Task management",
"SCRUM methodology",
"Agile methodology",
"Product management",
"Product roadmaps",
"User experience design",
"Programming skills",
"Product lifecycle management",
"QA testingng",
"Requirements gathering",
"Coding",
"Debugging",
"Implementation",
"Testing",
"Design",
"Configuration",
"Applications",
"Android",
"Security",
"Algorithms",
"Modeling",
"Documentation",
"IOS",
"Adobe creative",
"HTML",
"Interactive media",
"Wireframing",
"UX research",
"Prototyping",
"Color theory",
"Responsive design",
"Photoshop",
"Sketch",
"User modeling",
"Search Engine Optimization ",
"Digital media",
"Social media platforms",
"Automated marketing software",
"Content Management Systems ",
"Copywriting",
"Content creation",
"Google Analytics",
"Marketing analytics tools",
"Accounting",
"Word processing",
"Spreadsheet building",
"Coding",
"Programming",
"Operating equipment",
"Engineering",
"Experimenting",
"Testing",
"Constructing",
"Restoring",
"Product developing",
"Quality controlling",
"Blueprint drafting",
"Repairing",
"Translating",
"Speaking",
"Writing",
"Conversing",
"Reinterpreting",
"Public speaking",
"Following etiquette",
"Explaining",
"Respecting",
"Signaling",
"Proofreading",
"Introducing",
"Representing",
"Rephrasing",
"Code-switching",
"Graphic designing",
"Illustrating",
"Sketching",
"Architecture",
"User experience development",
"User interface development",
"Typography",
"Layout development",
"Web designing",
"Interior designing",
"Data visualizing",
"Hierarchical arranging",
"Aligning",
"Photo and video editing",
"Wireframing",
"Researching",
"Interpreting",
"Information processing",
"Organizing",
"Processing",
"Graphing",
"Computing",
"Calculating",
"Extrapolating",
"Predicting",
"Forecasting",
"Investigating",
"Surveying",
"Statistical analysis"
]